name: NKblank
main: be.noki_senpai.NKblank.NKblank
version: 0.0.1
api-version: 1.18
author: 'NoKi_senpai'
description: 'Blank NK plugin'
website: www.lumen.ovh
depend: [NKcore]
commands:
  mycommand:
    description: "a command"
    usage: /<command>
  mycommandwithsubcommands:
    description: "a command with subcommands"
    usage: /<command> <subcommand>